apiVersion: apps/v1
kind: Deployment
metadata:
  name: BookMyShow
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: cont-1
        image: shaikmustafa/paytm:movie
        ports:
        - containerPort: 80
